config/routes.rb
Forum::Application.routes.draw do

  resources :settings

  resources :topics do
    resources :posts
    member do
      get :block
      get :unblock
    end
  end

  resources :users

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signin' => 'sessions#create', :as => :signin
  match 'profile' => 'users#edit', :as => :profile
  match 'update_profile' => 'settings#update', :as => :update_profile

  root :to => 'users#index'

end

app/models/topic.rb
# -*- encoding : utf-8 -*-
class Topic < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true, length:{minimum: 2,maximum: 200}
  has_many :posts, order: "posts.created_at", dependent: :destroy
  def edit?(user)
    user && user.privilege?
  end
end

app/controllers/topics_controller.rb
# -*- encoding : utf-8 -*-
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  before_filter :not_authenticated, :except => [:index]
  before_filter :require_login, except: [:index, :show]
  before_filter :check_edit, only: [:edit, :update, :destroy, :block, :unblock]
  before_filter :check_show, only: :show
  def index
    @topics = Topic.order('updated_at DESC').page(params[:page])
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.includes(:posts => {:user => :setting}).find(params[:id])
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    if @topic.save
      redirect_to @topic,notice: 'Тема создана'
    else
      render 'new'
    end

    #respond_to do |format|
    #  if @topic.save
    #    format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
    #    format.json { render json: @topic, status: :created, location: @topic }
    #  else
    #    format.html { render action: "new" }
    #    format.json { render json: @topic.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

      if @topic.update_attributes(params[:topic])
        redirect_to @topic, notice: 'Тема изменена.'
      else
        render action: "edit"
      end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    redirect_to topics_path
  end
  def block
    @topic.blocked=true
    @topic.save
    flash[:success]="Топик заблокирован"
    redirect_to @topic
  end
  def unblock
    @topic.blocked=false
    @topic.save
    flash[:success]="Топик раблокирован"
    redirect_to @topic
  end
  private
    def check_edit
      @topic=Topic.find(params[:id])
      unless @topic.edit?(current_user)
        error_message
      end
    end
  private
  def check_show
    @topic=Topic.find(params[:id])
    if !@topic.edit?(current_user) && @topic.blocked?
      error-message("Топик заблокирован")
    end
  end
end

app/helpers/topics_helper.rb
# -*- encoding : utf-8 -*-
module TopicsHelper
end

app/views/topics/_form.html.haml
= form_for @topic do |f|
  =error_messages_for(@topic)
  =f.label :name
  =f.text_field :name,class: 'spans'
  .form-actions=f.submit nil,class: 'btn'

app/views/topics/edit.html.haml
.page-header
  %h1 Редактирование темы
= render 'form'
.btn-toolbar
  =link_to topics_path,class: 'btn' do
    %i.icon-arrow-left
    Назад
    %td=link_to "Показать", @topic,class:'btn'

app/views/topics/index.html.haml
.page-header
  %h1 Список тем
.btn-toolbar
  =link_to "Новая тема",new_topic_path,class:'btn'
%table.table.table-bordered
  %thread
    %tr
      %th=Topic.human_attribute_name(:name)
      %th=Topic.human_attribute_name(:updated_at)
      %th=Topic.human_attribute_name(:action_on)
  %tbody
  - @topics.each do |topic|
    %tr
      %td=link_to topic.name,topic
      %td=l(topic.updated_at)
      %td=link_to "Показать", topic,class:'btn'
      %td=link_to "Редактировать", edit_topic_path(topic),class:'btn'
      %td=link_to "Удалить", topic, :method => :delete, :data => { :confirm => 'Уверены?' },class:'btn'
=paginate @topics

app/views/topics/new.html.haml
.page-header
  %h1 Новая тема
= render 'form'

app/views/topics/show.html.haml
.page-header
  %h1=@topic.name
-if @topic.edit?(current_user)
  .btn-toolbar
    =link_to 'Редактировать',edit_topic_path(@topic),class:'btn'
    =link_to 'Удалить',@topic,data:{method: :delete,confirm: "Вы уверены?"},class:'btn btn-danger'
-if @topic.blocked?
  =link_to "Разблокировать",unblock_topic_path(@topic),class: 'btn'
-else
  =link_to "Заблокировать",block_topic_path(@topic),class: 'btn'
.btn-toolbar
  =link_to topics_path,class: 'btn' do
    %i.icon-arrow-left
    Назад
  %td=l(@topic.updated_at)
-@topic.posts.each do |post|
  =render 'posts/post',post: post
-if logged_in?
  =render 'posts/new'