config/routes.rb
Forum::Application.routes.draw do

  resources :settings

  resources :topics do
    resources :posts
    member do
      get :block
      get :unblock
    end
  end

  resources :users

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signin' => 'sessions#create', :as => :signin
  match 'profile' => 'users#edit', :as => :profile
  match 'update_profile' => 'settings#update', :as => :update_profile

  root :to => 'users#index'

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :email, :password, :password_confirmation, :username
  validates :username, presence: true, uniqueness: true, length:{minimum:5,maximum:80}
  validates :password, presence: true, length:{minimum:5}, confirmation: true
  validates :email, presence: true, uniqueness: true, format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  ROLES=["Пользователь","Модератор","Администратор"]
  validates :role, presence: true, inclusion:{in:0...ROLES.size}
  has_many :posts, order: "posts.created_at"
  has_one :setting

  def edit?
    current_user && (current_user.id==user_id || current_user.admin?)
  end
  def privilege?
    role>0
  end
  def user
    role==0
  end
  def admin?
    role==2
  end
user.setting=Setting.default
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  before_filter :require_login, except:[:new,:create,:show]
  #before_filter :check_admin, except:[:new,:create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user=current_user
    @setting = @user.setting
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.role=0
    setting=Setting.new
    setting.user=@user
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /users/1
  # PUT /users/1.json
  def update
   # @user = User.find(params[:id])
    @user=current_user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def update_all
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to profile_path :notice => "OK BLYA!"
    else
      flash[:error] = "не сохранено"
      render 'edit'
    end
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  =error_messages_for @user
  =f.label :username
  =f.text_field :username
  =f.label :email
  =f.email_field :email
  =f.label :password
  =f.password_field :password
  =f.label :password_confirmation
  =f.password_field :password_confirmation
  .form-actions
    =f.submit nil,class: 'btn btn-primary'

app/views/users/edit.html.haml
-if @user.errors.any?
  #error_explanation
    %h2= "Настройки Профиля"
%h3= "Стиль"
%div
=@user.setting.inspect
=form_for @user.setting, :url => update_profile_path, :html => {:multipart => true} do |f|
  .field
    = f.label :font
    = f.select :font, ([["Выбрать", "0"],["Arial"],["Comic Sans MS"],["Pompadur"],["sans-serif"],["cursive"],["fantasy"],["monospace"],["Times New Roman"]])


    = f.label :font_color
    = f.text_field :font_color


    = f.label :bg_color
    = f.text_field :bg_color


    = f.label :font_size
    = f.text_field :font_size


    = f.label :decoration
    = f.select :decoration,([["Выбрать", "0"],["Подчёркивание", "underline"],["Мигающий","blink"],["Линия над текстом", "overline"]])


    =f.label :caption
    =f.text_field :caption
  .actions
    = f.submit 'Сохранить', class: 'btn btn-warning'

= link_to 'Back', users_path, class: 'btn btn-warning'

app/views/users/index.html.haml
%h1 Пользователи

%table
  %tr
    %th Имя
    %th Пароль
    %th Salt
    %th Email
    %th Роль
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.username
      %td= user.password
      %td= user.salt
      %td= user.email
      %td= user.role
      %td= link_to 'Show', user, class: 'btn btn-inverse'
      %td= link_to 'Edit', edit_user_path(user), class: 'btn btn-inverse'
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-inverse'

%br

= link_to 'New User', new_user_path, class: 'btn btn-primary'

app/views/users/new.html.haml
.page-header
%h1 Регистрация нового пользователя

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
%p
  %b Password:
  = @user.password
%p
  %b Salt:
  = @user.salt
%p
  %b Email:
  = @user.email
%p
  %b Role:
  = @user.role

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path