config/routes.rb
Forum::Application.routes.draw do

  resources :settings

  resources :topics do
    resources :posts
    member do
      get :block
      get :unblock
    end
  end

  resources :users

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signin' => 'sessions#create', :as => :signin
  match 'profile' => 'users#edit', :as => :profile
  match 'update_profile' => 'settings#update', :as => :update_profile

  root :to => 'users#index'

end

app/models/post.rb
# -*- encoding : utf-8 -*-
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic,touch: true
  attr_accessible :body
  validates :user_id, presence:true
  validates :body,presence: true,length:{maximum: 2000}
  validates :topic_id,presence: true
  def edit?(current_user)
    current_user && (current_user.id==user_id || current_user.privilege?)
  end

end

app/controllers/posts_controller.rb
# -*- encoding : utf-8 -*-
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  before_filter :load_topic
  before_filter :require_login, except:[:index,:show]
  before_filter :check_edit, only:[:edit,:update,:destroy]
  def edit
    @post = @topic.posts.find(params[:id])
  end
      # POST /posts
  # POST /posts.json                                                nder
  def create
    @post = @topic.posts.new(params[:post])
    @post.user=current_user
    if @post.save
      redirect_to @topic,notice: 'Сообщение сохранено'
    else
      render :text => params[:post].inspect
    end

  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = @topic.posts.find(params[:id])
      if @post.update_attributes(params[:post])
        redirect_to @topic, notice: 'Сообщение отредактирово'
      else
        render action: "edit"
      end
    end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = @topic.posts.find(params[:id])
    @post.destroy
    redirect_to topic_path(@topic)
    end
  private
    def load_topic
      @topic=Topic.find(params[:topic_id])
    end
  private
  def check_edit
    @post=@topic.posts.find(params[:id])
    unless @post.edit?(current_user)
      error_message
    end
  end
end

app/helpers/posts_helper.rb
# -*- encoding : utf-8 -*-
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for [@topic,(@post||=Post.new)] do |f|
  =error_messages_for @post
  =f.label :body
  =f.text_area :body,class: 'span 8',rows: 5
  =f.submit nil,class: 'btn'
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

app/views/posts/_new.html.haml
%h1 Новое сообщение

= render 'posts/form'

app/views/posts/_post.html.haml
.post{ :style => "background: #{post.user.setting.bg_color};"}
  .title
    =post.user.username
    .pull-right=l(post.created_at,format: :long)
    .clearfix
  .body{ :style => "font-family: #{post.user.setting.font}; color: #{post.user.setting.font_color}; font-size: #{post.user.setting.font_size}; text-decoration: #{post.user.setting.decoration};"}=post.body
  =post.user.setting.caption
%table
  -if post.edit?(current_user)
    .btn-toolbar
      =link_to edit_topic_post_path(@topic,post),class: 'btn btn-mini' do
        %i.icon-edit
        Редактировать
      =link_to [@topic,post],class: 'btn btn-mini',data:{method: :delete,confirm:"Вы уверены?"} do
        %i.icon-trash
        Удалить

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %tr
    %th Body
    %th User
    %th Topic
    %th
    %th

  - @posts.each do |post|
    %tr
      %td= post.body
      %td= post.user
      %td= post.topic
      %td= link_to 'Show', post
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @post.body
%p
  %b User:
  = @post.user
%p
  %b Topic:
  = @post.topic

= link_to 'Edit', edit_post_path(@post)
= link_to 'Back', posts_path