config/routes.rb
Forum::Application.routes.draw do

  resources :settings

  resources :topics do
    resources :posts
    member do
      get :block
      get :unblock
    end
  end

  resources :users

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signin' => 'sessions#create', :as => :signin
  match 'profile' => 'users#edit', :as => :profile
  match 'update_profile' => 'settings#update', :as => :update_profile

  root :to => 'users#index'

end

app/views/layouts/_error.html.haml
-if object.errors.any?
  .alert.alert-error.alert-block
    %h4 При сохранении произошли ошибки
    %ul
      -object.errors.full_messages.each do |msg|
        %li=msg

app/views/layouts/_flash_messages.html.haml
-flash.each do |key,val|
  .alert{class: "alert-#{key}"}
    =val

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset=>'utf-8'}
    %title Форум
    =stylesheet_link_tag :application
    =javascript_include_tag :application
    =csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %ul.nav
            -if !logged_in?
              %li=link_to "Регистрация", new_user_path
          %ul.nav.pull-right
            -if logged_in?
              %btn-group
              %li.dropdown
                =link_to '#', data: {toggle: "dropdown"}, class: 'btn-primary dropdown-toggle' do
                  %i.icon-user.icon-white
                  =current_user.username
                  %b.caret
                %ul.dropdown-menu
                  %i.icon-home
                  =link_to "Главная", users_path
                  %br
                  %i.icon-list-alt
                  =link_to "Форум", topics_path
                  %li.divider
                  %i.icon-pencil
                  =link_to "Настройки", edit_user_path(current_user.id)
                  %br
                  %i.icon-off
                  =link_to "Выход", logout_path
            -else
              %li=link_to 'Войти',login_path
  .container
    .row=render 'layouts/flash_messages'
    =yield

app/views/layouts/error.html.haml
.alert.alert-error=@msg
.btn-toolbar
  =link_to topics_path,class: 'btn' do
    %i.icon-arrow-left
    Назад